<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>I-Have-My-Phone-Anyway</AssemblyName>
    <RootNamespace>IHaveMyPhoneAnyway</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TIMF.Abstractions\TIMF.Abstractions.csproj" />
  </ItemGroup>
</Project>
